"""
Django settings for noticeboard_api project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Detect if running in GitHub Codespaces
CODESPACE_NAME = os.getenv('CODESPACE_NAME')
GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dtf(bn^ryoezc)3fkk^kyzfsg!&)*zi!p1iq-xh$#yw&iihp)l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'api.noticeboard.co.zw',
    'localhost',
    '127.0.0.1',
    '*.app.github.dev',  # GitHub Codespaces
    '.gitpod.io',        # GitPod
    '.repl.co',          # Replit
    '*.ngrok.io',        # ngrok tunnels
    '*',                 # Allow all for development
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # DISABLED FOR DEVELOPMENT
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noticeboard_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noticeboard_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://127.0.0.1:8000",
]

# CSRF Settings - COMPLETELY DISABLED FOR DEVELOPMENT
CSRF_TRUSTED_ORIGINS = [
    'https://*.app.github.dev',  # GitHub Codespaces
    'https://*.gitpod.io',       # GitPod
    'https://*.repl.co',         # Replit
    'https://*.ngrok.io',        # ngrok tunnels
    'http://localhost:8000',     # Local development
    'http://127.0.0.1:8000',     # Local development
    'https://api.noticeboard.co.zw',  # Production
    'https://localhost:8000',
    'http://localhost:3000',     # Common frontend ports
    'http://localhost:3001',
    'http://localhost:5173',     # Vite default
    'http://localhost:4200',     # Angular default
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

LOGIN_URL = '/admin/'

# =============================================================================
# DEVELOPMENT ONLY: COMPLETELY DISABLE CSRF VERIFICATION
# =============================================================================
# WARNING: NEVER USE THESE SETTINGS IN PRODUCTION!

# Disable CSRF completely for development
CSRF_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_NAME = None

# Additional CSRF bypass settings
if 'runserver' in sys.argv or 'test' in sys.argv:
    # Running development server or tests
    CSRF_TRUSTED_ORIGINS = ['*']
    CSRF_COOKIE_DOMAIN = None
    
# Complete CSRF bypass
USE_CSRF = False

# Security settings for development
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_REFERRER_POLICY = None

# Session settings
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = None

print("🚀 Django settings loaded successfully!")
print(f"🔧 DEBUG mode: {DEBUG}")
print(f"📍 CSRF Protection: DISABLED (Development Only)")
if CODESPACE_NAME:
    print(f"☁️  Running in GitHub Codespace: {CODESPACE_NAME}")
